### ISSUE TITLE
Does not support promises

### ISSUE THREAD

**Issue by albertpeiro** [mie00/sails-elasticsearch#1]
It'd be nice if .search and the other methods supported them since bluebird is already a dependency.

Thank you for sharing this module!

**Comment by mie00** [comment]
https://github.com/mie00/sails-elasticsearch/commit/34da3c3447b6667ea4a3fb6ed90906835f90f5bc
I've made other methods in the adapter return a promise as well. It's not fully tested yet so it's under dev branch, until it's tested and then a new release will be made with these changes. (probably at the end of the week)
To use it for now you can inside package.json of your project change sails-elastic dependency to
`"sails-elastic": "mie00/sails-elasticsearch#dev",`.
If you find any issue with the new commit, it would be very helpful to file it.

**Comment by albertpeiro** [comment]
Brilliant! Will try it.
