### ISSUE TITLE
Multiple connections don't work (sails 0.12.1)

### ISSUE THREAD

**Issue by albertpeiro** [mie00/sails-elasticsearch#2]
After a long search, this is I think the best implementation of elastic search for sailsjs.
I'm trying to make it work with MongoDB, so I use the multiple connections in a model specified on the documentation.

models/Plant.js
`
...
connections: ['envMongodbServer','envElasticsearchServer'],
...
`

I get this error when trying to do this:
`Plant.search(query)`

`TypeError: Plant.search is not a function`

Any thoughts on why I'm getting this? Thank you so much for your great work and support!

**Comment by mie00** [comment]
I've tested it against

```
sails: 0.11.0
node: 0.12.0
elasticsearch: 2.3.3
sails-elastic: 0.11.03
```

and it works perfectly fine.
Can you make sure that the connection array is defined in Plant model as well, cause if you only define it in models/Person it will be applied only to this model.

Please tell me if you still have this issue.

**Comment by albertpeiro** [comment]
(I notice that you tried sails 0.11.0 but I'm using 0.12.1 as mentioned in the title)

package.json

```
"sails": "0.12.1",
"sails-elastic": "^0.11.3",
"sails-mongo": "^0.12.0",
```

```
node v4.2.1
npm 2.14.7
```

I'm using Elasticsearch version: 2.2.2

Sorry that was my bad I made sure I didn't make any mistake like what you mentioned. Basically this is what I have:

Plant.js:

```
connections: ['envMongodbServer', 'envElasticsearchServer'],
attributes: {
    slug: { type: 'string' },
    commonName: { type: 'string' }
},
elasticSearch: {
    mappings: {
      plant: {
        properties: {
          slug: {
            type: "string",
          },
          commonName: {
            type: "string",
          }
        }
      }
    }
  },
```

local.js

```
envElasticsearchServer: {
      adapter: 'sails-elastic',
      hosts: 'URL OF THE ELASTIC SEARCH',
      keepAlive: false,
      sniffOnStart: true,
      maxRetries: 10,
      deadTimeout: 40000,
      sniffOnConnectionFault: true,
      apiVersion: '2.2'
    },
```

and in connections I have the envMongodbServer, which works.

SearchController.js

```
...
Plant.search(query, function () {})
...
```

And get error:
`TypeError: Plant.search is not a function
`

**Comment by albertpeiro** [comment]
I tried replacing "connections" with just one connection like this...
Plant.js:
`connection: 'envElasticsearchServer'
`
and it seems to connect - though I'm not entirely sure - and throws this error when doing exactly the same code:

```
Plant.search()
```

```
{
msg: "[index_closed_exception] closed, with { index=plant }",
path: "/plant/_search",
query: { },
body: "a",
statusCode: 403,
response: "{"error":{"root_cause":[{"type":"index_closed_exception","reason":"closed","index":"plant"}],"type":"index_closed_exception","reason":"closed","index":"plant"},"status":403}",
message: "[index_closed_exception] closed, with { index=plant }",
stack: "Error: [index_closed_exception] closed, with { index=plant } at respond (ROOOT/node_modules/sails-elastic/node_modules/elasticsearch/src/lib/transport.js:293:15) at checkRespForFailure (ROOOT/node_modules/sails-elastic/node_modules/elasticsearch/src/lib/transport.js:252:7) at HttpConnector.<anonymous> (ROOOT/node_modules/sails-elastic/node_modules/elasticsearch/src/lib/connectors/http.js:155:7) at IncomingMessage.wrapper (ROOOT/node_modules/sails-elastic/node_modules/elasticsearch/node_modules/lodash/index.js:3095:19) at emitNone (events.js:72:20) at IncomingMessage.emit (events.js:166:7) at IncomingMessage.wrapped (ROOOT/node_modules/sails-hook-newrelic/node_modules/newrelic/lib/transaction/tracer/index.js:155:28) at IncomingMessage.wrappedEmit [as emit] (ROOOT/node_modules/sails-hook-newrelic/node_modules/newrelic/lib/transaction/tracer/index.js:187:46) at endReadableNT (_stream_readable.js:903:12) at wrapped (/ROOOT/node_modules/sails-hook-newrelic/node_modules/newrelic/lib/transaction/tracer/index.js:155:28) at doNTCallback2 (node.js:439:9) at process._tickDomainCallback (node.js:394:17) at process.wrappedFunction (ROOOT/node_modules/sails-hook-newrelic/node_modules/newrelic/lib/transaction/tracer/index.js:250:51)"
}
```

It seems to me like what's not working is the multiple connections pattern.

I have also printed the entire Plant object and done a find for the word "search" and this or any other of the expected elastic methods are not implemented in the object when I use Plant in the controller. I never redefine Plant or do any weird stuff, it's a fresh install with very simple setup. Plant.find() works okay.

**Comment by mie00** [comment]
Apparently sails 12 uses `connection` in the model definition instead of `connections`. Can you see if it works with you?

**Comment by mie00** [comment]
Ok, didn't see your last comment.
Can you try to create a record in elastic search first and see if the error still exists?

**Comment by albertpeiro** [comment]
This works (connection, instead of connections):
`connection: ['envMongodbServer', 'envElasticsearchServer'],`

Haven't managed to make a query work, because I don't know the syntax, but the create and update on the model do push to ElasticSearch.
Now getting ES syntax errors for search, and it connects :) 

Thanks a lot!
